services:
  proxy:
    build: .
    container_name: proxy
    ports:
      - "8080:8080"
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RESP_ADDRESS: "localhost:6382"
    working_dir: /app
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"